feat: Make an algorithm to recommend a coffee based on mood and weather
pinodo/coffee-mathcer pull request #26
Opened 2022-10-02 17:53 UTC by hard-working-developer

### Summary
  1. Implemented an algorithm to calculate the best coffee based on moods users have selected and the current weather.

### Steps to test
  1. I've tested some manual cases to see if the coffee recommendation function works. For now, I have not implemented how to test cuz we have not implemented the front-end component yet.

2022-10-03 03:49 UTC, KatelynKim requested changes
Looking good. Just a few suggestions :)

2022-10-03 03:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +        result += "cold "
Sorry, can we make this `iced` instead of cold?

2022-10-03 03:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +    // Pick up cofee.
Can we implement the logic for randomly selecting a coffee from multiple coffees with the same max score?

2022-10-09 15:27 UTC, hard-working-developer commented on src/lib/coffee-recommendation-algorithm.js
> +        result += "cold "
Changed the variable.

2022-10-09 15:27 UTC, hard-working-developer commented on src/lib/coffee-recommendation-algorithm.js
> +    // Pick up cofee.
Implemented it.

2022-10-09 20:49 UTC, KatelynKim requested changes

2022-10-09 20:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +function getCoffee (selectedMoods, temperature) {
```suggestion
function recommendCoffee (selectedMoodIDs, temperature) {
```

2022-10-09 20:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +    for(i = 0; i < total.length; i++) {
Could you extract this into a function?

2022-10-09 20:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +    if(maxIndex.length == 1) {
Is this conditional (maxIndex.length === 1) necessary? 
```suggestion
  
```

2022-10-09 20:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +    let total = [0,0,0,0,0]
Could we dynamically initialize `total` and rename it to `totalScoresArray`? 
```suggestion
    const totalScoresArray = new Array(coffees.length).fill(0)
```

2022-10-09 20:49 UTC, KatelynKim commented on src/lib/coffee-recommendation-algorithm.js
> +    for(let i = 0; i < selectedMoods.length; i++) {
Could you refactor this to be more readable and functional?

2022-10-09 20:49 UTC, KatelynKim commented on src/demo.js
> +import coffees from "./data/coffees"
Could you delete this file?

2022-10-11 00:01 UTC, KatelynKim approved these changes
LGTM

2022-10-11 00:01 UTC, merged